# docker-compose.yml
version: '3'
services:
  opencpu:
    volumes:
      - "./workspace:/home/opencpu:rw"
    build:
      context: ./opencpu
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 8004:8004
