---
title: "Abhängigkeiten"
output:
  html_document:
    self_contained: no
  pdf_document: default
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```


# Schedule

```{r schedule, fig.height=10, fig.width=10, include=FALSE}
snippet::init()
dt <- durationTable
kategorie <- c("SQM", "SBM", "SQM","SQM", "SBM", "SQM", "SQM", "SBM", "SQM", "SBM", "SBM", "PRC", "PRC", "PRC", "PRC", "PRC", "DMS", "DMS", "DMS", "SQM", "SQM", "SQM")
kdt <- tibble::tibble(Kategorie = kategorie, dt)
s <- snippet::schedulePlot()
```

```{r widget, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
s
```

# Flextable

```{r flextable, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}


 flextable::flextable(kdt)%>%
    flextable::add_header_row(top=TRUE,values = c("", "Lister der Aktivitäten mit Kategorie", "", "")) %>%
    flextable::theme_booktabs()%>%
    flextable::font(font="Segoe UI", part = "all")%>%
    flextable::add_footer_lines("Library: flextable     \n")%>%
    flextable::fontsize(size=10, part="all")%>%
    flextable::fontsize(size=7, part="footer")%>%
    flextable::align(j="Dauer",align="left", part="all")%>%
    flextable::autofit()%>%
    flextable::fit_to_width(max_width = 10.0, inc = 1L, max_iter = 20)
```
# ggplot
```{r}

ggplot2::ggplot((data= kdt)) + geom_bar(mapping = aes(x=kategorie))

ggplot2::ggplot(data= kdt, mapping = aes(x=kategorie, y=dauer)) + geom_boxplot()
ggplot2::ggplot(data= kdt, mapping = aes(x=dauer, y= ..density..)) + geom_freqpoly(mapping = aes(color=kategorie), binwidth=2)
```

